### ISSUE TITLE
Duplicated outputs (Help wanted!)

### ISSUE THREAD

**Issue by XxA7med66xX** [xvrh/chrome_extension.dart#19]
Hi,i use this library to get the current url from the current chrome tab and when I use `print` to print the url in console I get duplicated output everytime,whether I use `onUpdate` event Inside `onCreated` or use `onUpdate` alone so I was think is just issue because I use `print`  but the suprise is every code I writed gets duplicated in the excution, I don't know if I am writing it incorrectly or if there is a real issue with the library due to newer versions of Chrome, Thank you for this library.

![chrome_extention_issue](https://github.com/xvrh/chrome_extension.dart/assets/97599003/45e7386d-bc4c-477d-868d-102733d5e657)

The code

![code_snip](https://github.com/xvrh/chrome_extension.dart/assets/97599003/aa79ef2f-665e-41c9-b3a3-f5da60aff24e)

I also noticed that I get this error every time the link is printed in the console

![dart_error](https://github.com/xvrh/chrome_extension.dart/assets/97599003/970d268a-e8c7-41ba-9f68-3a3446a35dce)

## manifest.json 

![manifest](https://github.com/xvrh/chrome_extension.dart/assets/97599003/2c5bf208-d7c6-49c7-aa7e-d24cedffcabf)

## Some usefull information

- Chromium version: 120.0.6099.224 
- Dart SDK version: 3.2.0
- Flutter version: 3.16.0

**Comment by XxA7med66xX** [comment]
The build script I use

```dart 

import 'dart:io';

void main() async {
  
  await Process.run(
    'flutter',
    [
      'build',
      'web',
      '-t',
      'lib/main.dart',
      '--web-renderer',
      'html',
      '--csp',
    ],
  );

  await Process.run(
    'dart',
    [
      'compile',
      'js',
      'lib/background.dart',
      '--output',
      'build/web/background.dart.js',
    ],
  );
}
```

**Comment by xvrh** [comment]
I think it's normal that you receive several `onUpdated` events. It's fired every time something change in the tab and there are a lot of tracked properties.
Maybe I'm missing something from your description?

If you can share a reproducible example, I can have a better look.

**Comment by XxA7med66xX** [comment]
Sure, here is a short example of duplicated execution.

https://github.com/xvrh/chrome_extension.dart/assets/97599003/4348fa83-b9a7-4a74-bbdb-415ab5417a6a

What I want to do is when I visit a specific URL it remove the tab and create another tab with different URL, However, I cant do this correctly due to the duplication.

**Comment by MHQB** [comment]
> What I want to do is when I visit a specific URL it remove the tab and create another tab with different URL, However, I cant do this correctly due to the duplication.

Haven't tried but this should work:
```Dart
 chrome.tabs.onUpdated
      .where((event) => event.changeInfo.url?.contains('something') ?? false)
      .listen((event) => chrome.tabs
          .update(event.tabId, UpdateProperties(url: 'something else')));
```

**Comment by XxA7med66xX** [comment]
> Haven't tried but this should work:
> 
> ```dart
>  chrome.tabs.onUpdated
>       .where((event) => event.changeInfo.url?.contains('something') ?? false)
>       .listen((event) => chrome.tabs
>           .update(event.tabId, UpdateProperties(url: 'something else')));
> ```

Thank you so much this method works great no duplication anymore :)
