### ISSUE TITLE
chrome.desktopCapture.chooseDesktopMedia callback example

### ISSUE THREAD

**Issue by kantino789** [xvrh/chrome_extension.dart#25]
I am trying to use `chrome.desktopCapture.chooseDesktopMedia` the following way:

```
@JS()
external String test(String obj);

Future<bool> runProcess(String id) async {
  chrome.desktopCapture.chooseDesktopMedia([
    DesktopCaptureSourceType.screen,
    DesktopCaptureSourceType.tab,
    DesktopCaptureSourceType.window
  ], null, null, test.toJS);
  return true;
}
```

but I have some problems with the callback. I get 

```
lib/bot/run_process.dart:21:18: Error: Tear-offs of external top-level member 'test' are disallowed.
Declare a closure that calls this member instead.
  ], null, null, test.toJS);
```

when compiling.

Is it possible to get an example of how to create a JSFunction and how to pass it as a callback ? I checked the examples but couldn't find anything helpful.

**Comment by xvrh** [comment]
I think you can just have a callback like that:

```dart
Future<bool> runProcess(String id) async {
  chrome.desktopCapture.chooseDesktopMedia([
    DesktopCaptureSourceType.screen,
    DesktopCaptureSourceType.tab,
    DesktopCaptureSourceType.window
  ], null, null, ((String streamId, JSObject options) {
    print('Callback: $streamId');
  }).toJS);
  return true;
}
```

I guess you can also forward to your test method
```dart
@JS()
external String test(String obj);

Future<bool> runProcess(String id) async {
  chrome.desktopCapture.chooseDesktopMedia([
    DesktopCaptureSourceType.screen,
    DesktopCaptureSourceType.tab,
    DesktopCaptureSourceType.window
  ], null, null, ((String streamId, JSObject options) {
    test(streamId);
  }).toJS);
  return true;
}
```

Let me know if it helps.

**Comment by kantino789** [comment]
The samples seem ok, but now I get `Error: ApiNotAvailableException: chrome.desktopCapture is not available. Check that the manifest contains the correct permissions.`

even though I have the following in my web/manifest.json file
`"permissions": ["tabs", "desktopCapture"]`

**Comment by xvrh** [comment]
weird, it works for me with `desktopCapture` permission.
Can you setup a repository for a small reproduction?

**Comment by kantino789** [comment]
https://github.com/kantino789/flutter-capture-desktop-sample

My chrome version is `Version 124.0.6367.92 (Official Build) (64-bit)`

**Comment by xvrh** [comment]
Is it really a [chrome extension](https://developer.chrome.com/docs/extensions) that you are building?

I looks like a legacy chrome web app?

**Comment by kantino789** [comment]
Yes, my bad. I was trying to record any Chrome tab from a web app, but I am not sure if it is possible, even with other technologies than Flutter. I know it is indeed possible with an extension.

Thank you for your help, the issue can be closed !
