### ISSUE TITLE
[UNRELATED] Running with firebase remote config

### ISSUE THREAD

**Issue by pepealonso95** [xvrh/chrome_extension.dart#34]
Just wanted to know if you had any experience running with firebase remote config (or any firebase product). Your readme was incredibly helpful to run with canvaskit and wanted to know if you had any experience as they updated their documentation for running firebase without gstatic scripts which is supported by manifest but it looks like it belongs to an older version of flutter. https://firebase.google.com/docs/flutter/setup?platform=web#disable-auto

**Comment by EricPHassey** [comment]
I'm also wondering this. It seems like Flutter, Chrome Extension MV3, and Firebase are in no-mans-land right now. Tons of different ways to try, but no clue what works and what's best.

**Comment by pepealonso95** [comment]
managed to make this run by bundling firebase with webpack, seems to be the only working solution

**Comment by EricPHassey** [comment]
> managed to make this run by bundling firebase with webpack, seems to be the only working solution

I got it to work with webpack, however I wasn't able to get FlutterFire to work with Auth. It wouldn't authenticate. Not sure why or what happened. I had to actually add my credentials to js and use auth inside js to authenticate.
